export default {
  IDLE: 'IDLE',
  INIT: 'INIT',
  FINAL: 'FINAL',


  PRE_SPIN_START: 'PRE_SPIN_START',
  SPIN_START: 'SPIN_START',
  SPIN_STOP: 'SPIN_STOP',

  REQUEST_SPIN: 'REQUEST_SPIN',
  SHOW_WINNINGS: 'SHOW_WINNINGS',
  GET_SPIN_RESPONSE: 'GET_SPIN_RESPONSE'
}
